### ISSUE TITLE
[suggestion] - convertendo-um-class-based-component-para-react-hooks

### ISSUE THREAD

**Issue by ftonato** [willianjusten/willianjusten.com.br#102]
Willian, beleza?

Deixo abaixo algumas considerações;
Vale lembrar que talvez ela não façam sentido, neste caso, basta ignorar 😊

**Comment by ftonato** [comment]
**[current]** `... que possuía um valor inicial e também recebi uma atualização através do this.setState`
**[suggestion]** `... que possuía um valor inicial e também recebia uma atualização através do this.setState`

**Comment by ftonato** [comment]
**[current]** `... para que o useEffect fique sendo chamado toda vez que essas propriedades sejam atualizadas.`
**[suggestion]** `... para que o useEffect execute toda vez que essas propriedades sejam atualizadas.`

**Comment by ftonato** [comment]
**[current]** `... passando para qual o valor que desejamos mudar.`
**[suggestion]** `... passando o novo valor.`

**Comment by ftonato** [comment]
**[current]** `Vamos ver agora então, um antes/depois dos componentes inteiros. Abaixo segue o componente em classe que era antes:`
**[suggestion 1]** `Vamos ver agora então, um antes/depois dos componentes inteiros. Abaixo segue o componente utilizando classe (original):`
**[suggestion 2]** `Vamos ver agora então, um antes/depois dos componentes inteiros. Abaixo segue o componente utilizando classe (antes das nossas alterações):`

**Comment by ftonato** [comment]
**[current]** `E agora veja o mesmo componente, porém utilizando hooks:`
**[suggestion 1]** `E agora veja o mesmo componente, utilizando hooks, depois das nossas alterações:`
**[suggestion 2]** `Veja abaixo o componente, já com as nossas alterações, utilizando hooks:`

**Comment by ftonato** [comment]
**[current]** `a própria equipe do React diz para não querer sair convertendo tudo sem necessidade.`
**[suggestion]** `a própria equipe do React diz para não sairmos convertendo tudo sem necessidade.`

> Vale adicionar o link de onde a equipe do React diz isso? (https://reactjs.org/docs/hooks-faq.html#do-i-need-to-rewrite-all-my-class-components)

**Comment by willianjusten** [comment]
Muuiiiiito obrigado! Perfeito como sempre, acabei de mergear as mudanças!
