### ISSUE TITLE
[suggestion] - meus-15-dias-no-chile

### ISSUE THREAD

**Issue by ftonato** [willianjusten/willianjusten.com.br#114]
Willian, nice?

Segue as sugestões, mas lembre-se que se ela não façam sentido, neste caso, basta ignorar 😊

**Comment by ftonato** [comment]
**[current]** `Eu fiz essa viagem tem um tempinho já`
**[suggestion]** `Eu fiz essa viagem tem um tempinho ~já~`

**Comment by ftonato** [comment]
**[current]** `então resolvi escrever esse post aqui`
**[suggestion]** `por este motivo, compartilharei com vocês como fora minha experiência`

**Comment by ftonato** [comment]
**[current]** `só acessar a série`
**[suggestion]** `acesse a série`

**Comment by ftonato** [comment]
**[current]** `o é propaganda tá`
**[suggestion]** `o é propaganda`

**Comment by ftonato** [comment]
**[current]** `só buscar por`
**[suggestion]** `basta buscar por`

**Comment by ftonato** [comment]
**[current]** `E bom, não poderia ter sido uma companhia melhor`
**[suggestion]** `E não poderia ter sido uma companhia melhor`

**Comment by ftonato** [comment]
**[current]** `mas vimos que para a maioria desses`
**[suggestion]** `mas percebemos que para a maioria desses`

**Comment by ftonato** [comment]
**[current]** `em fazer a Patagônia`

Não entendi muito bem o que estavas tantando dizer com esta frase =(

**Comment by ftonato** [comment]
**[current]** `em viagens futuras`
**[suggestion]** `em futuras viagens`

**Comment by ftonato** [comment]
**[current]** `nós não desistimos de procurar lugares`
**[suggestion]** `não desistimos de procurar lugares`

**Comment by ftonato** [comment]
**[current]** `que desse para fazer trilhas`
**[suggestion]** `e que nos permitisse fazer trilhas`

**Comment by ftonato** [comment]
**[current]** `nós encontramos lugares muito bonitos`
**[suggestion]** `encontramos lugares muito bonitos`

**Comment by ftonato** [comment]
**[current]** `nós fomos definindo as outras partes.`
**[suggestion]** `nós começamos a definir as outras partes`

**Comment by ftonato** [comment]
**[current]** `Tiveram alguns passeios`
**[suggestion 1]** `Tivemos alguns passeios`
**[suggestion 2]** `Fizemos alguns passeios`

**Comment by ftonato** [comment]
**[current]** `que a gente só comia miojo todos os dias`
**[suggestion]** `que só podíamos comer miojo`

**Comment by ftonato** [comment]
**[current]** `mas também sem precisar dividir o quarto com 20 cabeças, que eu já to velho para isso.`
**[suggestion]** `mas também sem precisar dividir o quarto com 20 cabeças (btw, eu já to velho para isso).`

**Comment by ftonato** [comment]
**[current]** `A comida no Chile é realmente cara para caramba!`
**[suggestion 1]** `A comida no Chile é realmente cara!`
**[suggestion 2]** `A comida no Chile é cara demais!`
**[suggestion 3]** `A comida no Chile é realmente muito cara!`

**Comment by ftonato** [comment]
**[current]** `Se for fazer o passeio só por isso, nem vá.`
**[suggestion]** `Se for fazer o passeio só por isso, eu não recomendo.`

**Comment by ftonato** [comment]
**[current]** `Existe vulcão em tudo que é canto e você sempre se surpreende com a beleza deles.`
**[suggestion]** `Existem vulcões em tudo que é canto e você sempre se surpreende com a beleza deles.`

**Comment by ftonato** [comment]
**[current]** `Bom, essa é a explicação da viagem ter sido barata,`
**[suggestion]** `Essa é a explicação da viagem ter sido barata,`

**Comment by ftonato** [comment]
**[current]** `Mas bom, eu nem me incomodo com esse tipo de coisa, então para mim tá show, quanto mais barato melhor!`
**[suggestion]** `Eu não me incomodo com esse tipo de coisa, então para mim tá show, quanto mais barato melhor!`

**Comment by ftonato** [comment]
**[current]** `Eu vou postar os lugares que ficamos nos lugares.`
**[suggestion]** `Eu vou postar os lugares que ficamos.`

**Comment by ftonato** [comment]
**[current]** `Bom, como dito acima, o objetivo era aproveitar bem a região dos lagos`
**[suggestion]** `Como dito acima, o objetivo era aproveitar bem a região dos lagos`

**Comment by ftonato** [comment]
**[current]** `Então o que nós fizemos foi pegar um voo para Santiago e de lá para Puerto Montt.`
**[suggestion]** `Então, o que nós fizemos foi pegar um voo para Santiago e de lá para Puerto Montt.`

**Comment by ftonato** [comment]
**[current]** `Tudo no aeroporto de Santiago é caro, então o que nos salvou foram uns sanduíches e biscoitos que a Julia tinha levado`
**[suggestion]** `Tudo no aeroporto de Santiago é caro, o que nos salvou foram uns sanduíches e biscoitos que a Julia tinha levado`

**Comment by ftonato** [comment]
**[current]** `Julia tinha levado`
**[suggestion]** `Julia havia levado`

**Comment by ftonato** [comment]
**[current]** `Depois de todo esse tempo, nós chegamos bem a noite em Puerto Montt`
**[suggestion]** `Depois de todo esse tempo, chegamos bem a noite em Puerto Montt`

**Comment by ftonato** [comment]
**[current]** `já que não tinha mais ônibus e nós teríamos que pegar 2 para conseguir chegar no nosso destino, então saía mais barato pegar um Uber mesmo.`
**[suggestion]** `uma vez que já não havia mais ônibus e teríamos que embarcar em dois para conseguir chegar ao nosso destino, neste caso, fora mais barato/acessível pegar um Uber.`

**Comment by ftonato** [comment]
**[current]** `Nós ficamos somente por essa noite e na época deu`
**[suggestion]** `Nós ficamos somente por essa noite e na época o custo foi`

**Comment by ftonato** [comment]
> Em todos os lugares onde utilizas valores, aconselho adicionar o espaço entre a moeda (key) e valor (value)

**[current]** `R$5,00`
**[suggestion]** `R$ 5,00`

**Comment by ftonato** [comment]
**[current]** `que era o nosso objetivo, já que a cidade que iríamos de fato era Frutillar.`
**[suggestion]** `que era o nosso objetivo, visto que a cidade que iríamos era Frutillar.`

**Comment by ftonato** [comment]
**[current]** `nós nos arrumamos e fomos caminhando em direção a rodoviária`
**[suggestion]** `nos arrumamos e fomos caminhando em direção a rodoviária`

**Comment by ftonato** [comment]
**[current]** `para pegar um ônibus para Frutillar`
**[suggestion]** `embarcar em onibus com destino a Frutillar`

**Comment by ftonato** [comment]
**[current]** `o ônibus para lá custa aproximadamente R$5,00 e a viagem dura em torno de 1h.`
**[suggestion]** `o custo com este foi aproximadamente R$ 5,00 e a viagem durou em torno de 1h.`

**Comment by ftonato** [comment]
**[current]** `pesquisar um pouco sobre a região dos lagos`
**[suggestion]** `pesquisar sobre a região dos lagos`

**Comment by ftonato** [comment]
**[current]** `que tem vista para enorme e maravilhoso vulcão de Osorno`
**[suggestion]** `que tem vista para (um/o) enorme e maravilhoso vulcão de Osorno`

**Comment by ftonato** [comment]
**[current]** `Só que chegando lá, havia um aviso de fechado, porém com o portão aberto.`
**[suggestion]** `Quando chegamos lá, havia um aviso de fechado, porém com o portão aberto.`

**Comment by ftonato** [comment]
**[current]** `Nós "invadimos" a fazenda e acabamos descobrindo que estava tendo um casamento lá,`
**[suggestion]** `Nós "invadimos" a fazenda e acabamos descobrindo que estava acontecendo um casamento,`

**Comment by ftonato** [comment]
**[current]** `pegamos um ônibus`
>> Eu também utilizo a palavra "pegar" para dizer que embarco em um, mas é trão estranho =(

**Comment by ftonato** [comment]
**[current]** `parque são 6 dólares`
**[suggestion]** `foram $ 6 (seis doláres)`

**Comment by ftonato** [comment]
**[current]** `Esse ônibus você pega na rodoviária de Puerto Varas`
**[suggestion]** `Vocês podem entrar neste ônibus na rodoviária de Puerto Varas`

**Comment by ftonato** [comment]
**[current]** `Bom, o maior objetivo dessa minha viagem`
**[suggestion]** `Chegamos ao maior objetivo dessa minha viagem`

**Comment by ftonato** [comment]
**[current]** `podendo ser possível lava!`
**[suggestion]** `podendo ser possível ver lava!`

**Comment by ftonato** [comment]
**[current]** `mas ainda irei retornar lá e chegar até o final!`
**[suggestion 1]** `mas ainda retornarei para chegar até o final!`
**[suggestion 2]** `mas ainda pretendo retornar a ele e alcançar o topo!`

**Comment by ftonato** [comment]
**[current]** `ela me convenceu a ir numa das termas que ela já ia`

> **Iria ir** OU **ia** no sentido de já conhecia e frequenta?

**Comment by ftonato** [comment]
**[current]** `ainda tem uma cachoeira!`
**[suggestion]** `ainda é agraciado por uma cachoeira!`

**Comment by ftonato** [comment]
**[current]** `resolvemos ir lá e também nos arredores`
**[suggestion]** `resolvemos visitá-la e seus arredores`

**Comment by ftonato** [comment]
**[current]** `Lá em Valparaíso`
**[suggestion]** `Em Valparaíso`

**Comment by ftonato** [comment]
**[current]** `Outra coisa que Valparaíso é famosa são os seus morros e olha`
**[suggestion]** `Outra coisa que em Valparaíso é famosa são seus morros e olha`

**Comment by ftonato** [comment]
**[current]** `Bom, essa era a cidade que menos ficamos`
**[suggestion]** `Essa foi a cidade que menos ficamos`

**Comment by ftonato** [comment]
**[current]** `Lá nós basicamente focamos em fazer uma visitação na mais antiga vinícula do Chile`
**[suggestion]** `Uma vez lá, basicamente focamos em fazer uma visitação na mais antiga vinícula do Chile`

**Comment by ftonato** [comment]
**[current]** `E porque do`
**[suggestion]** `O motivo de ter usado o +/-`

**Comment by ftonato** [comment]
**[current]** `vá bem mais cedo`
**[suggestion]** `vá cedo`

**Comment by ftonato** [comment]
**[current]** `nós despedimos`
**[suggestion 1]** `nós nos despedimos`
**[suggestion 2]** `nos despedimos`

**Comment by ftonato** [comment]
**[current]** `lagos e vulcões. Então essa parte é perfeita para você`
**[suggestion]** `lagos e vulcões, então essa parte é perfeita para você`

**Comment by ftonato** [comment]
**[current]** `então se você quiser usar alguma para wallpaper`
**[suggestion]** `sinta-se livre para usar alguma para/como wallpaper`

**Comment by ftonato** [comment]
**[current]** `que perguntou e bom, eu adoro viajar`
**[suggestion]** `que perguntou e como adoro viajar`

**Comment by willianjusten** [comment]
MUIIIIIIIIIIITO OBRIGADO! Suas revisões são ESPETACULARES!
