### ISSUE TITLE
[suggestion] - diga-não-ao-medium

### ISSUE THREAD

**Issue by ftonato** [willianjusten/willianjusten.com.br#118]
**Will**, nice?

**Note:** Segue as sugestões, mas lembre-se que se ela não façam sentido, neste caso, basta ignorar 😊

**Comment by ftonato** [comment]
**[current]** `Provavelmente será um post curto, mas a ideia é que ele seja usado para referência e discussão.`
**[suggestion]** `Provavelmente será um post curto e a ideia é que ele seja usado como referência em discussão.`

**Comment by ftonato** [comment]
**[current]** `Na minha opinião, uma das melhores bandas para se ouvir enquanto está trabalhando.`
**[suggestion 1]** `Na minha opinião, uma das melhores bandas para se ouvir enquanto estamos trabalhando.`
**[suggestion 2]** `Na minha opinião, uma das melhores bandas para se ouvir enquanto se está trabalhando.`

**Comment by ftonato** [comment]
**[current]** `Existe um site bem bacaninha que trouxe esse assunto a um tempo atrás`
**[suggestion 1]** `Existe um site bem bacaninha que trouxe esse assunto há um tempo`
**[suggestion 2]** `Existe um site bem bacaninha que trouxe esse assunto há um tempo atrás`

**Comment by ftonato** [comment]
**[current]** `Eu vou colocar somente algumas das razões e isso`
**[suggestion 1]** `Eu adicionarei somente algumas das razões e isso`
**[suggestion 2]** `Eu compartilharei somente algumas das razões e isso`

**Comment by ftonato** [comment]
**[current]** `Já começa aí a sua descredibilização.`
**[suggestion]** `A descredibilização começa por aí.`

**Comment by ftonato** [comment]
**[current]** `já perdeu a importância.`
**[suggestion 1]** `já perdeu a relavância.`
**[suggestion 2]** `já perdeu a importância e/ou relavância.`

**Comment by ftonato** [comment]
**[current]** `as vezes o retorno é até menor do que se fosse no seu próprio blog.`
**[suggestion]** `às vezes o retorno é até menor do que se fosse em seu próprio blog.`

**Comment by ftonato** [comment]
**[current]** `Quando você crie seu próprio blog`
**[suggestion 1]** `Quando você cria seu próprio blog`
**[suggestion 2]** `Quando você cria seu blog pessoal`

**Comment by ftonato** [comment]
**[current]** `fazer com as pessoas se sintam parte do meu blog`
**[suggestion]** `fazer com que as pessoas se sintam parte do meu blog`

**Comment by ftonato** [comment]
**[current]** `As vezes é difícil saber por onde começar a contribuir no Github`
**[suggestion]** `Às vezes é difícil saber por onde começar a contribuir no Github`

**Comment by ftonato** [comment]
**[current]** `Enfim, existem várias razões para você ter sua própria plataforma, seja para aprender, seja para crescer sua imagem na web, seja para ajudar os outros e ganhar colaborações.`
**[suggestion]** `Enfim, existem várias razões para você ter sua própria plataforma, seja para aprender, crescer sua imagem na web, ou até mesmo ajudar os outros e ganhar colaborações.`

**Comment by willianjusten** [comment]
Fixed and merged here #119
