### ISSUE TITLE
[Suggestion] Please issue a confusion with Git course for Windows users

### ISSUE THREAD

**Issue by gusbemacbe** [willianjusten/willianjusten.com.br#161]
Hello @willianjusten !

Sorry if this issue is unrelated to this repository, because you do not offer the direct contact, but suggested us to contact on any social networks, including GitHub. I opted for GitHub.

My friend is a Windows user and is learning your Git and GitHub course, contacted me, telling he had problems with Git and Shell commands, but he was not aware that you were using Shell commands and Command Prompt is not a Bash/Shell terminal. I suggested him to use PowerShell instead.

The Windows users who are learning Git with you, can get confused and not be aware that you are a macOS user and using the Shell commands that do not exist in the Command Prompt.

I suggest you fill an apology and an issue for Windows users who are students of your Git and GitHub course. In the issue, I suggest you make a small detail or comment, suggesting the Windows users to use PowerShell or activated WSL (Windows Subsystem for Linux). 

Observe that you do not need to fill an issue for Linux users as Linux and macOS are Unix cousins and share the same Shell.

**Comment by willianjusten** [comment]
Already discussed via Twitter DM, so I'll close this one, since it's a bit disconnected to the repository itself.
