### ISSUE TITLE
Adicionar sessão de Slacks da comunidade

### ISSUE THREAD

**Issue by yanmagale** [willianjusten/willianjusten.com.br#18]
Olá Will :D 

No post sobre como se manter atualizado no mercado de front-end, uma das ferramentas que tem ajudado bastante é o Slack. Apesar de ser utilizado para diversos fins e possibilitar interação, em muitos canais dele as pessoas costumam mandar links sobre novas tecnologias, blog posts e etc, sobre o tema daquele canal. Acha válido citar este canal no post?

[Neste repositório](https://github.com/joselitojunior1/slack-list-brazil) tem uma lista de links com uma lista de Slacks da comunidade Brasileira.

**Comment by willianjusten** [comment]
Eu confesso que não sou muito adepto de nenhum chat para esse tipo de coisa, porque acho que chats são muito vivos e se você não ficar 100% do tempo ali, acaba não conseguindo acompanhar de jeito nenhum e isso acaba até frustrando...

Mas vou separar um espaço para isso então.

**Comment by kvnol** [comment]
Já tentei também, algumas vezes, participar dos grupos no Slack mas não consegui me adaptar pelo mesmo motivo que o @willianjusten citou, muita gente, os assuntos voam muito rápido. Eu me adaptaria melhor com Slack numa equipe, mas para comunidade acho que não funciona pra mim.
