### ISSUE TITLE
When click on search it opens the menu up. Is it intentional? 

### ISSUE THREAD

**Issue by dutraneto** [willianjusten/willianjusten.com.br#245]
https://github.com/willianjusten/willianjusten.com.br/blob/8e7cf85df0ff64d4a024162c084aad7984b0f3f0/src/components/MenuBar/index.js#L49

**Comment by willianjusten** [comment]
Uh, nope, that's probably something that I left in the migration and didn't notice. Can you send a PR fixing it?
