### ISSUE TITLE
Novo Visual Blog 2017

### ISSUE THREAD

**Issue by willianjusten** [willianjusten/willianjusten.com.br#37]
Você acompanha meu blog e quer me ajudar? Todo ano eu crio um visual para o meu blog, esse ano eu resolvi pensar diferente. O blog é feito para a comunidade e porque não ser feito pela comunidade também?

E como ajudar?

Você é designer? Que tal ajudar com propostas de novos visuais?
Você é dev? Que tal ajudar na programação?
Você é iniciante e quer ajudar? Que tal ajudar com testes, revisões e pequenas tarefas?
Você não tem a mínima noção de nada, mas quer ajudar? Que tal você dar sua opinião do que você acha que poderia melhorar na usabilidade do blog?

Enfim, eu obviamente estarei trabalhando com tudo, seja revisando visual, código, performance (sim, me preocupo com isso xD), então também é uma oportunidadade para também trabalhar do meu lado ~~e descobrir que sou bem merda =p~~

Eu vejo esse processo em algumas etapas, mas a etapa inicial seria:

- Discussão de features/usabilidades
- Apresentação de novos visuais/ideias

Então essa issue vai ficar aberta para discutirmos sobre tudo! =D

E aí? Animou? Já vai colocando suas opiniões e rabiscos aí!

**Comment by yesroh** [comment]
Quero ajudar com testes, revisões e pequenas tarefas :)

**Comment by AiCoutoS** [comment]
Essa é a fonte do Medium, usei ela no [Hacker Gaucho](http://blog.hackergaucho.com/). 

Deixei como estava no Medium, mas tem seletores que podem ser removidos.
```
    h1,h2,h3,h4{
        font-family: medium-content-sans-serif-font,"Lucida Grande","Lucida Sans Unicode","Lucida Sans",Geneva,Arial,sans-serif;
    }
    h1{
        color: rgba(0, 0, 0, 0.8);
        font-feature-settings: "liga";
        font-size: 40px;
        font-style: normal;
        font-weight: 700;
        letter-spacing: -1.11667px;
        line-height: 41.6px;
        margin-bottom: 0px;
        margin-left: -2.5px;
        margin-right: 0px;
        margin-top: 0px;
        overflow-wrap: break-word;
        text-rendering: optimizelegibility;
        visibility: visible;
    }
    p,li,td{
        font-family: medium-content-serif-font,Georgia,Cambria,"Times New Roman",Times,serif;
        font-feature-settings: "liga";
        font-size: 21px;
        font-style: normal;
        font-weight: 400;
        line-height: 33.1833px;
    }
    p {
        clearleftcolor: rgba(0, 0, 0, 0.8);
        font-feature-settings: "liga";
        letter-spacing: -0.0666667px;
        margin:14px 0;
        overflow-wrap: break-word;
        text-rendering: optimizelegibility;
        visibility: visible;
    }
```

**Comment by AiCoutoS** [comment]
Fiz um [grid css de 1kb](https://github.com/AiCoutoS/1k) com suporte básico ao markdown. Quero manter ele abaixo de 1024 bytes e tornar o grid fluido para não precisar [usar Bootstrap](http://blog.hackergaucho.com/post/Antes_e_depois_do_Bootstrap). 

`bower install 1k`

**Comment by willianjusten** [comment]
O problema style que você mandou é basicamente `medium-content-sans-serif-font`, que já indica fonte própria deles. Outra coisa é que de fato existem propriedades bem estranhas...

Mas como eu disse, essa primeira etapa é mais para:

- Discussão de features/usabilidades
- Apresentação de novos visuais/ideias

**Comment by vinirossi** [comment]
Sou iniciante quero ajudar com testes, revisões e pequenas tarefas. Se der poderia tentar com desenvolvimento, mas não sei, inseguro ainda. Seu blog atual tá fodástico, não sei se  consigo melhorar aqui rs

**Comment by GeysaPriscila** [comment]
Sou iniciante, tenho um conhecimento básico em html, js, php, mysql tenho
interesse em ajudar com revisões, pequenas tarefas, testes e se possivel
com programação também rsrs', acredito que com isso também posso ampliar
meus conhecimentos na área!

Em 1 de fevereiro de 2017 21:44, vinirossi <notifications@github.com>
escreveu:

**Comment by willianjusten** [comment]
Ano passado num rolou, mas esse ano já to me movendo, vou fechar aqui para abrir umas coisas em separado.
