### ISSUE TITLE
Remover o zepto que nem precisa

### ISSUE THREAD

**Issue by willianjusten** [willianjusten/willianjusten.com.br#53]
Basicamente só tem 2 pontos usando o Zepto, que podem ser facilmente modificados:

- [zmain.js](https://github.com/willianjusten/willianjusten.com.br/blob/master/src/js/zmain.js)
- [SimpleJekyllSearch](https://github.com/willianjusten/willianjusten.com.br/blob/master/src/js/simpleJekyllSearch.js)

Sobre o Jekyll Search, [já tem versão pura em JS](https://github.com/christian-fei/Simple-Jekyll-Search), então só remover esse velho e adaptar

**Comment by iagolaguna** [comment]
Aonde esta sendo usado o zepto sera feito em JS puro sem nenhuma lib auxiliar  essa é a ideia?

**Comment by willianjusten** [comment]
Sim... Mas como eu pretendia mudar o tema, eu meio deixei para lá.

**Comment by willianjusten** [comment]
Se quiser contribuir, vai na fé =D
Os lugares que usam são os apontados ali.
