### ISSUE TITLE
Sobre o Redesign do Blog

### ISSUE THREAD

**Issue by willianjusten** [willianjusten/willianjusten.com.br#54]
Sobre alguns pontos a considerar:

- Muita gente acessa o blog e muita gente acaba pedindo posts que já até existem. Então seria interessante criar uma solução melhor sobre isso, como posts relacionados dentro do post ou algo que os faça achar.
- O hero é horrível, sério, como eu pude fazer um treco tão feio e mal feito assim?
- A área de share fica muito escondida e isso diminui muito o número de cliques, seria legal fazer algo que fosse andando com a tela ou sei lá, algo que faça a galera compartilhar mais.
- A tipografia nova usando fontes do sistema tá bacana, mas os espaçamentos não estão nada legais, melhorar isso.
- A home tem uma separação boa até, mas um touch ali pode ser legal.
- Queria colocar algum lugar sobre fotografia/viagem, que eu tenho focado bastante.
- Facilitar as pessoas a acharem as páginas, mudar o menu talvez?

**Comment by ribeiroevandro** [comment]
Acho que posts relacionados seria algo bem irado. Posso tentar ajudar em algumas das implementações, preciso praticar o que tenho estudado e sou tão sem vergonha que pra mim eu enrolo e procrastino ao extremo, mas fazendo com alguém ou para alguém, me animo mais ^-^

Pontos que certamente eu poderia ajudar com 100% de certeza: 

- Fixar e deixar o share acompanhando o conteúdo ao rolar a página;
- Alterar o menu certamente ira fazer muita diferença, o menu hambúrguer é algo que causa discussões longas sobre seu uso. 

Depois te mando inbox para trocar umas ideias e até me ajudar no direcionamento do que fazer e como seria legal...

**Comment by willianjusten** [comment]
Devido ao tempo, acabei nem mexendo nessas coisas. Eu cheguei a fazer uma área de posts relacionados sim, mas botei que o uso nem é tão grande assim...
