### ISSUE TITLE
[suggestion] - habemus-react-hooks

### ISSUE THREAD

**Issue by ftonato** [willianjusten/willianjusten.com.br#98]
Hello Willian, tudo certo?

Estou lendo sobre o post (citado no título), e tenho algumas sugestões ~bobinhas~ sobre o texto, listarei elas abaixo a medida que for lendo...

Se julgares não interessantes, ignore-as por favor :)

> Já deixo aqui o meu agradecimento sobre a nova postagem 🕺

**Comment by ftonato** [comment]
> [current] ... `se você já leu tudo lá e já entendeu`
> [suggestion] ... `se você já leu ela e já entendeu`

> [current] ... `mas não vai embora ainda não, veja que belo gatinho.`
> [suggestion] ... `mas não vá embora ainda não, veja que belo gatinho.`

**Comment by ftonato** [comment]
ótima para concentrar e para quem curte jogos, aconselho demais a dar uma olhada

**Comment by ftonato** [comment]
Acabei fechando a _issue_ sem querer =(

**Comment by ftonato** [comment]
> Acredito que o último `agora` possa ser suprimido.

**[current]** `agora poderão ser simplificados na nova lógica dos hooks, além de poderem ser compartilhados agora.`
**[suggestion]** `agora poderão ser simplificados na nova lógica dos hooks, além de poderem ser compartilhados.`

**Comment by ftonato** [comment]
> A sugestão abaixo não sei se faz sentido 😶 

**[current]** `como uma não tão boa minificação e outros detalhes mais baixo nível.`
**[suggestion]** `como uma não tão boa minificação e outros detalhes de mais baixo nível.`

**Comment by ftonato** [comment]
> A sugestão abaixo não sei se faz sentido v2 😶 

**[current]** `para facilitar a entender o funcionamento.`
**[suggestion 1]** `para facilitar o entendimento.`
**[suggestion 2]** `para ajudar a entender o funcionamento.`

**Comment by ftonato** [comment]
> A frase expressa o "nós" implicitamente: "no nosso exemplo", talvez o "nós" que segue na frase também possa ser suprimido

**[current]** `No nosso exemplo, nós estamos alterando somente a`
**[suggestion]** `No nosso exemplo, estamos alterando somente a`

**Comment by ftonato** [comment]
**[current]** `se precisamos guardar dois diferentes valores `
**[suggestion]** `se precisarmos guardar dois diferentes valores `

**Comment by ftonato** [comment]
> A frase começa com `Ali nós declaramos a variável`, então este segundo `nós` talvez esteja sobrando 🤔 

**[current]** `como seu valor inicial e nós criamos o método`
**[suggestion]** `como seu valor inicial e criamos o método`

**Comment by ftonato** [comment]
**[current]** `precisávamos buscar lá no nosso objeto`
**[suggestion]** `precisávamos buscar no nosso objeto`

**Comment by ftonato** [comment]
**[current]** `Acima nós vimos como trabalhar com o`
**[suggestion 1]** `Acabamos de ver como trabalhar com o`
**[suggestion 2]** `Vimos acima como trabalhar com o`

**Comment by ftonato** [comment]
> Fiquei na dúvida nesse trecho, se depois de escrever duas palavras (nomes de métodos) em inglês o cérebro colocou aquele `and` de forma automática ou se fez de forma proposital.
> Independente do cenário, eu gosto do `and` mais do que do `e`, mas se foi no automático, talvez devesse realmente alterar para o `e`...

**[current]** `no 'componentDidMount', 'componentDidUpdate', and 'componentWillUnmount'?`

**Comment by willianjusten** [comment]
Foi no automático, o certo deveria ser "e" mesmo.

**Comment by ftonato** [comment]
> A frase começa com `mas`, então ter outro `mas` é como se estivessemos negando o que foi dito até agora (que já é uma negação da frase anterior), em outras palavras:

```js
const hasErrors = true;
!!hasErrors;
```

**[current]** `Mas em algumas ocasiões nossos componentes precisam “vigiar” enquanto estiverem na tela, mas depois precisamos limpar isso`
**[suggestion 1]** `Mas em algumas ocasiões nossos componentes precisam “vigiar” enquanto estiverem na tela e depois precisamos limpar isso`
**[suggestion 2]** `Mas em algumas ocasiões nossos componentes precisam “vigiar” enquanto estiverem na tela e depois limpar isso`

**Comment by ftonato** [comment]
> Olha o bug da sexta trollando novamente `or`:

**[current]** `Não chame Hooks dentro de loops, condicionais or funções aninhadas.`

🤣

**Comment by ftonato** [comment]
**[current]** `mas isso não seria muito o ideal né`
**[suggestion 1]** `mas isso não seria o ideal né`
**[suggestion 2]** `mas isso não seria o ideal, né?`
**[suggestion 3]** `mas isso não seria o ideal`

**Comment by willianjusten** [comment]
> **[current]** `mas isso não seria muito o ideal né`
> **[suggestion 1]** `mas isso não seria o ideal né`
> 
> > A sugestão abaixo não sei se faz sentido v3 😶
> 
> **[suggestion 2]** `mas isso não seria o ideal, né?`
> **[suggestion 3]** `mas isso não seria o ideal`

Acho que vou só com:

`mas isso não seria muito o ideal, olhe abaixo:`

**Comment by ftonato** [comment]
Okay, remover o `né` faz sentido, mas minha dúvida é realmente sobre o `muito`:
- `mas isso não seria muito o ideal, olhe abaixo:`

O "não seria muito" quer dizer que seria _um pouco_ o ideal? Acredito que não seria "um pouco" ideal não, repetir o código não seria bom nunca (meu ponto de vista) hahaha

----
**[question]**

Na explicação da class `FriendListItem`, mais especificamente no render, existe o seguinte trecho de código:

```js
return (
  <li style=>// está correta esta linha? 🤔 
    {props.friend.name}
  </li>
);
```

**Comment by willianjusten** [comment]
Ah, sobre essa parte do código, era um bug do Liquid (to usando o Jekyll ainda), mas já era para estar corrigido, dá um force refresh aí.

**Comment by ftonato** [comment]
**[current]** `ou faríamos através do render props ou`
**[suggestion]** `através do render props ou`

**Comment by ftonato** [comment]
> A sugestão abaixo não sei se faz sentido v4 😶

**[current]** `Nós decidimos o que ele irá receber como argumentos e também o que iremos retornar e se vamos retornar algo.`
**[suggestion]** `Nós decidimos o que ele irá receber como argumentos e também o que iremos retornar se precisarmos retornar algo.`

**Comment by ftonato** [comment]
**[question]** Como foi dito no artigo, `O 'useEffect' roda toda vez que renderiza?`

> Sim, por padrão ele vai rodar logo após ser renderizado e toda vez que for atualizado.

Senti falta apenas de um cenário que vou tentar explicar abaixo:

```js
// !hook
componentDidMount() {
  document.title = `You clicked ${this.state.count} times`;
}

componentDidUpdate() {
  document.title = `You clicked ${this.state.count} times`;
}

// hook
useEffect(() => {
  document.title = `You clicked ${count} times`;
});
```

Se tivermos um comportamento diferenciado para o `didMount` e `didUpdate`, existe alguma maneira simples de fazer isso com os Hooks usando só um effect?

> Sim, depois de pesquisar, cheguei a uma solução simples, e acho que vale listar algo parecido no artigo...

```js
// Com isto conseguimos saber se é a primeira vez que estamos executando a função `useEffect`
// para termos um comportamento diferenciado (se quisermos)...

const { useState, useRef, useEffect } = React;

function ComponentDidMountFunctionTest() {
  const [count, setCount] = useState(0);

  // https://reactjs.org/docs/hooks-faq.html#is-there-something-like-instance-variables
  const didMount = useRef(true);
  useEffect(() => {
    if (didMount.current) {
      console.log('It\'s your first time here');
      didMount.current = false;
      return;
    }
    
    console.log(`You clicked ${count} times`);
});

  return (
    <div>
      <h2>Open console to see the result</h2>
      <p>ComponentDidMountFunctionTest: {count} times</p>
      <button
        onClick={() => {
          setCount(count + 1);
        }}
      >
        Click Me
      </button>
    </div>
  );
}

ReactDOM.render(
  <ComponentDidMountFunctionTest />,
  document.getElementById("app")
);
```

**Comment by ftonato** [comment]
That's it!

Obrigado pela paciência, espero ter ajudado de alguma forma 🚀
